export const skills: { skill: string; icon: string }[] = [
  { skill: "HTML", icon: "/icons/html.svg" },
  { skill: "Markdown - MDX", icon: "/icons/markdown.svg" },
  { skill: "CSS", icon: "/icons/css.svg" },
  { skill: "Material UI", icon: "/icons/mui.svg" },
  { skill: "Tailwind", icon: "/icons/tailwind.svg" },
  { skill: "CSS Modules", icon: "/icons/css.svg" },
  { skill: "Typescript", icon: "/icons/ts.svg" },
  { skill: "Javascript", icon: "/icons/js.svg" },
  { skill: "React", icon: "/icons/react.svg" },
  { skill: "Next.js", icon: "/icons/nextjs.svg" },
  { skill: "Astro", icon: "/icons/astro.svg" },
  { skill: "Sanity", icon: "/icons/sanity.svg" },
  { skill: "Git", icon: "/icons/git.svg" },
  { skill: "GitHub", icon: "/icons/github.svg" },
  { skill: "Visual Studio Code", icon: "/icons/vscode.svg" },
];
