import type { Metadata } from 'next';

// Components
import { ThemeProvider } from '@/components/theme-provider';

// Styles
import './globals.css';

// Fonts
import { geistSans } from '@/lib/fonts';
import { Hero } from '@/sections/hero';

export const metadata: Metadata = {
  title: 'Ignacio Figueroa - Software Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="container">
            <Hero />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
